### ISSUE TITLE
Asking for PHP code spills over textarea

### ISSUE THREAD

**Issue by oleteacher** [bladealex9848/ChatGPT#2]
Really nice php for openai, thanks for sharing.

When asking questions like:  write php code to make simple flat file cms

Output starts in textarea but then spills over (outside) the textarea. Running the question will show you eamle of what I mean.

Like to use your ChatGPT example in classroom but cannot understand how to fix above issue.

Any ideas?

**Comment by bladealex9848** [comment]
If you can, give me a screenshot showing the problem, or an ulr to try.

**Comment by oleteacher** [comment]
I had closed because found another solution, but I do really like yours;)

Unfortunately, the dev server is local and no internet access to it.

Using your code without mod only added our key.

Here are couple of screenshots. The PHP code is being executed in the textarea it seems.

In prompt: `write php example for textarea submit form`
![image](https://user-images.githubusercontent.com/26278259/219804479-adb34416-5afb-4fcf-957e-85051115ebe6.png)

in promopt: `write php code for form save to text file`
![image](https://user-images.githubusercontent.com/26278259/219804594-f025381c-297b-4ab5-bb09-12717b17b039.png)
